### ISSUE TITLE
Hyper 3.1.1-serenade loses prompt and causes shutdown (Mac 10.14.6)

### ISSUE THREAD

**Issue by jeremyschultz** [serenadeai/hyper#3]
I replaced Hyper 3.1.4 with this Serenade version but encountered a variety of issues (running macOS 10.14.6 Mojave):

- Plugins > Update appears to do nothing
- After ~ 5 seconds or a click on the Hyper screen, all prompts and text go away. The terminal is black. The cursor is still where it was and it appears to accept input, but no characters are shown. A return just drops the cursor directly down to the next line (doesn't move to beginning of line).
- When I installed it I was running on battery power at ~30%. My laptop started going black and required a restart. At one point I could see power was now at 6%. After a few more restarts I went home to get on to the power cord, and I've not seen it since.

I've now replaced this with regular 3.1.4 and see no issues.

**Comment by jeremyschultz** [comment]
I see Mojave isn't supported by Apple anymore so you might not want to troubleshoot this. If not just keep it as an FYI in case it manifests again elsewhere.

**Comment by tmacwill** [comment]
Thanks for the report, and apologies for the delayed response! Hyper has since released the 3.1.x line on their stable channel, so we don't need our 3.1.1 version anymore. I removed references to the Serenade Hyper fork from the install instructions.
